/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new session (login) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate the current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminate the current session (logout) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend the current session expiry */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clinic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search for clinic records
         * @description GET /api/v2/clinic[?thisClinic=1|publicID=...|shortName=...]
         */
        get: operations["searchClinics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/icd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search ICD-10 codes
         * @description GET /api/v2/icd[?q=...&t=...&c=...&language=...&sort=...]
         */
        get: operations["searchIcdCodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/icd/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single ICD-10 code
         * @description GET /api/v2/icd/{code}[?language=en]
         */
        get: operations["getIcdCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a patient by clinic patient ID
         * @description GET /api/v2/patients/{id}
         */
        get: operations["getPatient"];
        put?: never;
        post?: never;
        /**
         * Deactivate a patient record (soft delete)
         * @description DELETE /api/v2/patients/{id}
         */
        delete: operations["deletePatient"];
        options?: never;
        head?: never;
        /**
         * Update a patient record
         * @description PATCH /api/v2/patients/{id}
         */
        patch: operations["updatePatient"];
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search patients
         * @description GET /api/v2/patients[?q=...&lastName=...&...]
         */
        get: operations["searchPatients"];
        put?: never;
        /**
         * Create a new patient record
         * @description POST /api/v2/patients
         */
        post: operations["createPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a staff member by username
         * @description GET /api/v2/staff/{username}
         */
        get: operations["getStaffMember"];
        put?: never;
        post?: never;
        /**
         * Deactivate a staff member (soft delete)
         * @description DELETE /api/v2/staff/{username}
         */
        delete: operations["deleteStaffMember"];
        options?: never;
        head?: never;
        /**
         * Update a staff member
         * @description PATCH /api/v2/staff/{username}
         */
        patch: operations["updateStaffMember"];
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List staff members
         * @description GET /api/v2/staff[?position=...&active=...]
         */
        get: operations["listStaff"];
        put?: never;
        /**
         * Create a new staff member
         * @description POST /api/v2/staff
         */
        post: operations["createStaffMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a visit by patient visit ID
         * @description GET /api/v2/visits/{id}
         */
        get: operations["getVisit"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a visit record
         * @description DELETE /api/v2/visits/{id}
         */
        delete: operations["deleteVisit"];
        options?: never;
        head?: never;
        /**
         * Update a visit record
         * @description PATCH /api/v2/visits/{id}
         */
        patch: operations["updateVisit"];
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search visits by patient or status
         * @description GET /api/v2/visits?clinicPatientID=...&visitStatus=...
         */
        get: operations["searchVisits"];
        put?: never;
        /**
         * Open a new visit
         * @description POST /api/v2/visits
         */
        post: operations["createVisit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Clinic: {
            /** @example 1 */
            clinicID: number;
            /**
             * @description 1 if this is the local clinic record
             * @example 1
             */
            thisClinic: number;
            /** @example PUB001 */
            publicID?: string | null;
            typeCode?: string | null;
            careLevel?: string | null;
            /** @example Community Health Clinic */
            longName?: string | null;
            /** @example CHC */
            shortName?: string | null;
            /** @example USD */
            currency?: string | null;
            address1?: string | null;
            address2?: string | null;
            clinicNeighborhood?: string | null;
            clinicCity?: string | null;
            clinicState?: string | null;
            clinicRegion?: string | null;
            clinicDirector?: string | null;
            clinicService?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            /** Format: date-time */
            createdDate?: string | null;
        };
        IcdCode: {
            /**
             * @example en
             * @enum {string}
             */
            language: "en" | "es";
            /** @example J06.9 */
            icd10code: string;
            /** @example J069 */
            icd10index: string;
            /** @example Acute upper respiratory infection, unspecified */
            shortDescription?: string | null;
            /** @example 12 */
            useCount: number;
            /**
             * Format: date
             * @example 2026-04-01
             */
            lastUsedDate?: string | null;
        };
        Patient: {
            /** @example PT-001 */
            clinicPatientID: string;
            patientNationalID?: string | null;
            familyID?: string | null;
            /** @example Smith */
            lastName: string;
            lastName2?: string | null;
            /** @example Jane */
            firstName: string;
            middleInitial?: string | null;
            /**
             * @example F
             * @enum {string}
             */
            sex: "M" | "F" | "X";
            /**
             * Format: date
             * @example 1985-06-15
             */
            birthDate?: string | null;
            /** Format: date */
            nextVaccinationDate?: string | null;
            homeAddress1?: string | null;
            homeAddress2?: string | null;
            homeNeighborhood?: string | null;
            homeCity?: string | null;
            homeCounty?: string | null;
            homeState?: string | null;
            contactPhone?: string | null;
            contactAltPhone?: string | null;
            /** @enum {string|null} */
            bloodType?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-" | "NA" | null;
            /** @example 0 */
            organDonor?: number | null;
            /** @enum {string|null} */
            preferredLanguage?: "en" | "es" | "ui" | null;
            knownAllergies?: string | null;
            currentMedications?: string | null;
            responsibleParty?: string | null;
            maritalStatus?: string | null;
            profession?: string | null;
        };
        Session: {
            /**
             * @description Immutable value object representing the session data returned to clients.
             *
             *     Only the fields safe to expose are included here; the full session row
             *     (sessionIP, sessionUA, etc.) is handled internally by the repository.
             * @example abc123def456
             */
            token: string;
            /** @example jsmith */
            username: string;
            /**
             * @example ClinicStaff
             * @enum {string}
             */
            accessGranted: "SystemAdmin" | "ClinicAdmin" | "ClinicStaff" | "ClinicReadOnly";
            /**
             * @example en
             * @enum {string}
             */
            sessionLanguage: "en" | "es" | "ui";
            /** @example PUB001 */
            sessionClinicPublicID?: string | null;
            /**
             * Format: date-time
             * @example 2026-04-06 12:00:00
             */
            expiresOnDate: string;
        };
        Staff: {
            /** @description Staff member — password is never included. */
            memberID?: string | null;
            /** @example jsmith */
            username: string;
            /** @example Smith */
            lastName: string;
            /** @example Jane */
            firstName: string;
            /**
             * @example Nurse
             * @enum {string}
             */
            position: "Nurse" | "NursesAid" | "NursingStudent" | "DoctorGeneral" | "DoctorSpecialist" | "MedicalStudent" | "ClinicStaff" | "Other";
            /**
             * @description 1 if clinical position, 0 if admin/other
             * @example 1
             */
            medicalStaff: number;
            /** @enum {string|null} */
            preferredLanguage?: "en" | "es" | "ui" | null;
            preferredClinicPublicID?: string | null;
            contactInfo?: string | null;
            altContactInfo?: string | null;
            /** @example 1 */
            active: number;
            /**
             * @example ClinicStaff
             * @enum {string}
             */
            accessGranted: "SystemAdmin" | "ClinicAdmin" | "ClinicStaff" | "ClinicReadOnly";
            /** Format: date-time */
            lastLogin?: string | null;
            /** Format: date-time */
            modifiedDate?: string | null;
            /** Format: date-time */
            createdDate?: string | null;
        };
        Visit: {
            /** @example 000000000001202604010101 */
            patientVisitID: string;
            /** @example PT-001 */
            clinicPatientID: string;
            /**
             * @example NO
             * @enum {string}
             */
            firstVisit: "YES" | "NO";
            patientNationalID?: string | null;
            patientFamilyID?: string | null;
            staffName?: string | null;
            staffUsername?: string | null;
            staffPosition?: string | null;
            /** @example Clinic */
            visitType: string;
            /**
             * @example Open
             * @enum {string}
             */
            visitStatus: "Open" | "Closed" | "Deleted";
            primaryComplaint?: string | null;
            secondaryComplaint?: string | null;
            /** Format: date-time */
            dateTimeIn?: string | null;
            /** Format: date-time */
            dateTimeOut?: string | null;
            payment?: string | null;
            /** @example Smith */
            patientLastName: string;
            /** @example Jane */
            patientFirstName: string;
            /** @enum {string} */
            patientSex: "M" | "F" | "X";
            /** Format: date */
            patientBirthDate?: string | null;
            patientHomeAddress1?: string | null;
            patientHomeAddress2?: string | null;
            patientHomeNeighborhood?: string | null;
            patientHomeCity?: string | null;
            patientHomeCounty?: string | null;
            patientHomeState?: string | null;
            patientContactPhone?: string | null;
            patientContactAltPhone?: string | null;
            patientKnownAllergies?: string | null;
            patientCurrentMedications?: string | null;
            /** Format: date */
            patientNextVaccinationDate?: string | null;
            patientResponsibleParty?: string | null;
            patientMaritalStatus?: string | null;
            patientProfession?: string | null;
            /** Format: float */
            height?: number | null;
            /** @enum {string|null} */
            heightUnits?: "cm" | "in" | null;
            /** Format: float */
            weight?: number | null;
            /** @enum {string|null} */
            weightUnits?: "kg" | "lb" | null;
            /** Format: float */
            temp?: number | null;
            /** @enum {string|null} */
            tempUnits?: "C" | "F" | null;
            bpSystolic?: number | null;
            bpDiastolic?: number | null;
            pulse?: number | null;
            glucose?: number | null;
            glucoseUnits?: string | null;
            diagnosis1?: string | null;
            condition1?: string | null;
            diagnosis2?: string | null;
            condition2?: string | null;
            diagnosis3?: string | null;
            condition3?: string | null;
            referredTo?: string | null;
            referredFrom?: string | null;
        };
        Error: {
            /**
             * @description Top-level OpenAPI definition for the piClinic v2 API.
             *     swagger-php scans this file for the @OA\Info, @OA\Server, and
             * @example error
             */
            status: string;
            /** @example Resource not found */
            message: string;
        };
        SuccessMessage: {
            /** @example success */
            status: string;
            data: {
                message?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example jsmith */
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            /** @description Missing credentials */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            /** @description Session invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        /** @example null */
                        data?: unknown;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Session"];
                    };
                };
            };
            /** @description Session invalid or expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchClinics: {
        parameters: {
            query?: {
                /** @description Return the local clinic record (value: 1) */
                thisClinic?: "1";
                /** @description Filter by public ID */
                publicID?: string;
                /** @description Filter by short name */
                shortName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching clinics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Clinic"][];
                };
            };
            /** @description No valid search parameter provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchIcdCodes: {
        parameters: {
            query?: {
                /** @description Search code or description text */
                q?: string;
                /** @description Search description text only */
                t?: string;
                /** @description Search by code prefix */
                c?: string;
                /** @description Language for descriptions (default en) */
                language?: "en" | "es";
                /** @description Sort field: c=code, t=description, d=last used date */
                sort?: "c" | "t" | "d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching ICD-10 codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcdCode"][];
                };
            };
            /** @description No search parameter provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getIcdCode: {
        parameters: {
            query?: {
                /** @description Language for description (default en) */
                language?: "en" | "es";
            };
            header?: never;
            path: {
                /** @description ICD-10 code (e.g. J06.9) */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICD-10 code found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IcdCode"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Clinic patient ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deletePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Clinic patient ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessMessage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updatePatient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Clinic patient ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Patient"];
            };
        };
        responses: {
            /** @description Patient updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchPatients: {
        parameters: {
            query?: {
                /** @description Free-text search across name fields */
                q?: string;
                /** @description Filter by last name */
                lastName?: string;
                /** @description Filter by first name */
                firstName?: string;
                /** @description Filter by clinic patient ID */
                clinicPatientID?: string;
                /** @description Filter by national ID */
                patientNationalID?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of matching patients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Patient"][];
                };
            };
            /** @description No search parameters provided */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Patient"];
            };
        };
        responses: {
            /** @description Patient created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Patient"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Patient ID already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getStaffMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Staff username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staff member found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteStaffMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Staff username */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staff member deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessMessage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateStaffMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Staff username */
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Staff"];
            };
        };
        responses: {
            /** @description Staff member updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listStaff: {
        parameters: {
            query?: {
                /** @description Filter by position */
                position?: "Nurse" | "NursesAid" | "NursingStudent" | "DoctorGeneral" | "DoctorSpecialist" | "MedicalStudent" | "ClinicStaff" | "Other";
                /** @description Filter by active status */
                active?: "0" | "1" | "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of staff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"][];
                };
            };
            /** @description Invalid filter value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createStaffMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example jsmith */
                    username: string;
                    /** @example Smith */
                    lastName: string;
                    /** @example Jane */
                    firstName: string;
                    /** @enum {string} */
                    position: "Nurse" | "NursesAid" | "NursingStudent" | "DoctorGeneral" | "DoctorSpecialist" | "MedicalStudent" | "ClinicStaff" | "Other";
                    /** Format: password */
                    password: string;
                    /** @enum {string} */
                    accessGranted: "SystemAdmin" | "ClinicAdmin" | "ClinicStaff" | "ClinicReadOnly";
                };
            };
        };
        responses: {
            /** @description Staff member created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Staff"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Username already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Patient visit ID (22-character composite key) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visit found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Patient visit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visit deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessMessage"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Patient visit ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Visit"];
            };
        };
        responses: {
            /** @description Visit updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    searchVisits: {
        parameters: {
            query: {
                /** @description Clinic patient ID */
                clinicPatientID: string;
                /** @description Filter by visit status */
                visitStatus?: "Open" | "Closed" | "Deleted";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of visits */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visit"][];
                };
            };
            /** @description clinicPatientID is required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createVisit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example PT-001 */
                    clinicPatientID: string;
                    /** @example Clinic */
                    visitType: string;
                    /** Format: date-time */
                    dateTimeIn?: string;
                    /** @example jsmith */
                    staffUsername?: string;
                    primaryComplaint?: string;
                };
            };
        };
        responses: {
            /** @description Visit opened */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example success */
                        status?: string;
                        data?: components["schemas"]["Visit"];
                    };
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
