<?php
declare(strict_types=1);

namespace PiClinic\Models;

use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: 'Visit',
    required: ['patientVisitID', 'clinicPatientID', 'firstVisit', 'visitType', 'visitStatus', 'patientLastName', 'patientFirstName', 'patientSex'],
    properties: [
        // Identity
        new OA\Property(property: 'patientVisitID',            type: 'string',  example: '000000000001202604010101'),
        new OA\Property(property: 'clinicPatientID',           type: 'string',  example: 'PT-001'),
        new OA\Property(property: 'firstVisit',                type: 'string',  enum: ['YES', 'NO'], example: 'NO'),
        new OA\Property(property: 'patientNationalID',         type: 'string',  nullable: true),
        new OA\Property(property: 'patientFamilyID',           type: 'string',  nullable: true),
        // Staff
        new OA\Property(property: 'staffName',                 type: 'string',  nullable: true),
        new OA\Property(property: 'staffUsername',             type: 'string',  nullable: true),
        new OA\Property(property: 'staffPosition',             type: 'string',  nullable: true),
        // Visit metadata
        new OA\Property(property: 'visitType',                 type: 'string',  example: 'Clinic'),
        new OA\Property(property: 'visitStatus',               type: 'string',  enum: ['Open', 'Closed', 'Deleted'], example: 'Open'),
        new OA\Property(property: 'primaryComplaint',          type: 'string',  nullable: true),
        new OA\Property(property: 'secondaryComplaint',        type: 'string',  nullable: true),
        new OA\Property(property: 'dateTimeIn',                type: 'string',  format: 'date-time', nullable: true),
        new OA\Property(property: 'dateTimeOut',               type: 'string',  format: 'date-time', nullable: true),
        new OA\Property(property: 'payment',                   type: 'string',  nullable: true),
        // Patient snapshot
        new OA\Property(property: 'patientLastName',           type: 'string',  example: 'Smith'),
        new OA\Property(property: 'patientFirstName',          type: 'string',  example: 'Jane'),
        new OA\Property(property: 'patientSex',                type: 'string',  enum: ['M', 'F', 'X']),
        new OA\Property(property: 'patientBirthDate',          type: 'string',  format: 'date', nullable: true),
        new OA\Property(property: 'patientHomeAddress1',       type: 'string',  nullable: true),
        new OA\Property(property: 'patientHomeAddress2',       type: 'string',  nullable: true),
        new OA\Property(property: 'patientHomeNeighborhood',   type: 'string',  nullable: true),
        new OA\Property(property: 'patientHomeCity',           type: 'string',  nullable: true),
        new OA\Property(property: 'patientHomeCounty',         type: 'string',  nullable: true),
        new OA\Property(property: 'patientHomeState',          type: 'string',  nullable: true),
        new OA\Property(property: 'patientContactPhone',       type: 'string',  nullable: true),
        new OA\Property(property: 'patientContactAltPhone',    type: 'string',  nullable: true),
        new OA\Property(property: 'patientKnownAllergies',     type: 'string',  nullable: true),
        new OA\Property(property: 'patientCurrentMedications', type: 'string',  nullable: true),
        new OA\Property(property: 'patientNextVaccinationDate', type: 'string', format: 'date', nullable: true),
        new OA\Property(property: 'patientResponsibleParty',   type: 'string',  nullable: true),
        new OA\Property(property: 'patientMaritalStatus',      type: 'string',  nullable: true),
        new OA\Property(property: 'patientProfession',         type: 'string',  nullable: true),
        // Vitals
        new OA\Property(property: 'height',      type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'heightUnits', type: 'string', nullable: true, enum: ['cm', 'in']),
        new OA\Property(property: 'weight',      type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'weightUnits', type: 'string', nullable: true, enum: ['kg', 'lb']),
        new OA\Property(property: 'temp',        type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'tempUnits',   type: 'string', nullable: true, enum: ['C', 'F']),
        new OA\Property(property: 'bpSystolic',  type: 'integer', nullable: true),
        new OA\Property(property: 'bpDiastolic', type: 'integer', nullable: true),
        new OA\Property(property: 'pulse',       type: 'integer', nullable: true),
        new OA\Property(property: 'glucose',     type: 'integer', nullable: true),
        new OA\Property(property: 'glucoseUnits', type: 'string', nullable: true),
        // Diagnoses
        new OA\Property(property: 'diagnosis1', type: 'string', nullable: true),
        new OA\Property(property: 'condition1', type: 'string', nullable: true),
        new OA\Property(property: 'diagnosis2', type: 'string', nullable: true),
        new OA\Property(property: 'condition2', type: 'string', nullable: true),
        new OA\Property(property: 'diagnosis3', type: 'string', nullable: true),
        new OA\Property(property: 'condition3', type: 'string', nullable: true),
        // Referrals
        new OA\Property(property: 'referredTo',   type: 'string', nullable: true),
        new OA\Property(property: 'referredFrom', type: 'string', nullable: true),
    ]
)]
readonly class Visit
{
    public function __construct(
        // Identity
        public string  $patientVisitID,
        public string  $clinicPatientID,
        public string  $firstVisit,
        public ?string $patientNationalID,
        public ?string $patientFamilyID,
        // Staff
        public ?string $staffName,
        public ?string $staffUsername,
        public ?string $staffPosition,
        // Visit metadata
        public string  $visitType,
        public string  $visitStatus,
        public ?string $primaryComplaint,
        public ?string $secondaryComplaint,
        public ?string $dateTimeIn,
        public ?string $dateTimeOut,
        public ?string $payment,
        // Patient snapshot (copied at visit creation)
        public string  $patientLastName,
        public string  $patientFirstName,
        public string  $patientSex,
        public ?string $patientBirthDate,
        public ?string $patientHomeAddress1,
        public ?string $patientHomeAddress2,
        public ?string $patientHomeNeighborhood,
        public ?string $patientHomeCity,
        public ?string $patientHomeCounty,
        public ?string $patientHomeState,
        public ?string $patientContactPhone,
        public ?string $patientContactAltPhone,
        public ?string $patientKnownAllergies,
        public ?string $patientCurrentMedications,
        public ?string $patientNextVaccinationDate,
        public ?string $patientResponsibleParty,
        public ?string $patientMaritalStatus,
        public ?string $patientProfession,
        // Vitals
        public ?float  $height,
        public ?string $heightUnits,
        public ?float  $weight,
        public ?string $weightUnits,
        public ?float  $temp,
        public ?string $tempUnits,
        public ?int    $bpSystolic,
        public ?int    $bpDiastolic,
        public ?int    $pulse,
        public ?int    $glucose,
        public ?string $glucoseUnits,
        // Diagnoses
        public ?string $diagnosis1,
        public ?string $condition1,
        public ?string $diagnosis2,
        public ?string $condition2,
        public ?string $diagnosis3,
        public ?string $condition3,
        // Referrals
        public ?string $referredTo,
        public ?string $referredFrom,
    ) {}

    /** @param array<string,mixed> $row */
    public static function fromRow(array $row): self
    {
        return new self(
            patientVisitID:           (string) ($row['patientVisitID']           ?? ''),
            clinicPatientID:          (string) ($row['clinicPatientID']          ?? ''),
            firstVisit:               (string) ($row['firstVisit']               ?? 'NO'),
            patientNationalID:        isset($row['patientNationalID'])        ? (string) $row['patientNationalID']        : null,
            patientFamilyID:          isset($row['patientFamilyID'])          ? (string) $row['patientFamilyID']          : null,
            staffName:                isset($row['staffName'])                ? (string) $row['staffName']                : null,
            staffUsername:            isset($row['staffUsername'])            ? (string) $row['staffUsername']            : null,
            staffPosition:            isset($row['staffPosition'])            ? (string) $row['staffPosition']            : null,
            visitType:                (string) ($row['visitType']                ?? ''),
            visitStatus:              (string) ($row['visitStatus']              ?? 'Open'),
            primaryComplaint:         isset($row['primaryComplaint'])         ? (string) $row['primaryComplaint']         : null,
            secondaryComplaint:       isset($row['secondaryComplaint'])       ? (string) $row['secondaryComplaint']       : null,
            dateTimeIn:               isset($row['dateTimeIn'])               ? (string) $row['dateTimeIn']               : null,
            dateTimeOut:              isset($row['dateTimeOut'])              ? (string) $row['dateTimeOut']              : null,
            payment:                  isset($row['payment'])                  ? (string) $row['payment']                  : null,
            patientLastName:          (string) ($row['patientLastName']          ?? ''),
            patientFirstName:         (string) ($row['patientFirstName']         ?? ''),
            patientSex:               (string) ($row['patientSex']               ?? ''),
            patientBirthDate:         isset($row['patientBirthDate'])         ? (string) $row['patientBirthDate']         : null,
            patientHomeAddress1:      isset($row['patientHomeAddress1'])      ? (string) $row['patientHomeAddress1']      : null,
            patientHomeAddress2:      isset($row['patientHomeAddress2'])      ? (string) $row['patientHomeAddress2']      : null,
            patientHomeNeighborhood:  isset($row['patientHomeNeighborhood'])  ? (string) $row['patientHomeNeighborhood']  : null,
            patientHomeCity:          isset($row['patientHomeCity'])          ? (string) $row['patientHomeCity']          : null,
            patientHomeCounty:        isset($row['patientHomeCounty'])        ? (string) $row['patientHomeCounty']        : null,
            patientHomeState:         isset($row['patientHomeState'])         ? (string) $row['patientHomeState']         : null,
            patientContactPhone:      isset($row['patientContactPhone'])      ? (string) $row['patientContactPhone']      : null,
            patientContactAltPhone:   isset($row['patientContactAltPhone'])   ? (string) $row['patientContactAltPhone']   : null,
            patientKnownAllergies:    isset($row['patientKnownAllergies'])    ? (string) $row['patientKnownAllergies']    : null,
            patientCurrentMedications: isset($row['patientCurrentMedications']) ? (string) $row['patientCurrentMedications'] : null,
            patientNextVaccinationDate: isset($row['patientNextVaccinationDate']) ? (string) $row['patientNextVaccinationDate'] : null,
            patientResponsibleParty:  isset($row['patientResponsibleParty'])  ? (string) $row['patientResponsibleParty']  : null,
            patientMaritalStatus:     isset($row['patientMaritalStatus'])     ? (string) $row['patientMaritalStatus']     : null,
            patientProfession:        isset($row['patientProfession'])        ? (string) $row['patientProfession']        : null,
            height:                   isset($row['height'])                   ? (float)  $row['height']                   : null,
            heightUnits:              isset($row['heightUnits'])              ? (string) $row['heightUnits']              : null,
            weight:                   isset($row['weight'])                   ? (float)  $row['weight']                   : null,
            weightUnits:              isset($row['weightUnits'])              ? (string) $row['weightUnits']              : null,
            temp:                     isset($row['temp'])                     ? (float)  $row['temp']                     : null,
            tempUnits:                isset($row['tempUnits'])                ? (string) $row['tempUnits']                : null,
            bpSystolic:               isset($row['bpSystolic'])               ? (int)    $row['bpSystolic']               : null,
            bpDiastolic:              isset($row['bpDiastolic'])              ? (int)    $row['bpDiastolic']              : null,
            pulse:                    isset($row['pulse'])                    ? (int)    $row['pulse']                    : null,
            glucose:                  isset($row['glucose'])                  ? (int)    $row['glucose']                  : null,
            glucoseUnits:             isset($row['glucoseUnits'])             ? (string) $row['glucoseUnits']             : null,
            diagnosis1:               isset($row['diagnosis1'])               ? (string) $row['diagnosis1']               : null,
            condition1:               isset($row['condition1'])               ? (string) $row['condition1']               : null,
            diagnosis2:               isset($row['diagnosis2'])               ? (string) $row['diagnosis2']               : null,
            condition2:               isset($row['condition2'])               ? (string) $row['condition2']               : null,
            diagnosis3:               isset($row['diagnosis3'])               ? (string) $row['diagnosis3']               : null,
            condition3:               isset($row['condition3'])               ? (string) $row['condition3']               : null,
            referredTo:               isset($row['referredTo'])               ? (string) $row['referredTo']               : null,
            referredFrom:             isset($row['referredFrom'])             ? (string) $row['referredFrom']             : null,
        );
    }

    /** @return array<string,mixed> */
    public function toArray(): array
    {
        return [
            'patientVisitID'           => $this->patientVisitID,
            'clinicPatientID'          => $this->clinicPatientID,
            'firstVisit'               => $this->firstVisit,
            'patientNationalID'        => $this->patientNationalID,
            'patientFamilyID'          => $this->patientFamilyID,
            'staffName'                => $this->staffName,
            'staffUsername'            => $this->staffUsername,
            'staffPosition'            => $this->staffPosition,
            'visitType'                => $this->visitType,
            'visitStatus'              => $this->visitStatus,
            'primaryComplaint'         => $this->primaryComplaint,
            'secondaryComplaint'       => $this->secondaryComplaint,
            'dateTimeIn'               => $this->dateTimeIn,
            'dateTimeOut'              => $this->dateTimeOut,
            'payment'                  => $this->payment,
            'patientLastName'          => $this->patientLastName,
            'patientFirstName'         => $this->patientFirstName,
            'patientSex'               => $this->patientSex,
            'patientBirthDate'         => $this->patientBirthDate,
            'patientHomeAddress1'      => $this->patientHomeAddress1,
            'patientHomeAddress2'      => $this->patientHomeAddress2,
            'patientHomeNeighborhood'  => $this->patientHomeNeighborhood,
            'patientHomeCity'          => $this->patientHomeCity,
            'patientHomeCounty'        => $this->patientHomeCounty,
            'patientHomeState'         => $this->patientHomeState,
            'patientContactPhone'      => $this->patientContactPhone,
            'patientContactAltPhone'   => $this->patientContactAltPhone,
            'patientKnownAllergies'    => $this->patientKnownAllergies,
            'patientCurrentMedications' => $this->patientCurrentMedications,
            'patientNextVaccinationDate' => $this->patientNextVaccinationDate,
            'patientResponsibleParty'  => $this->patientResponsibleParty,
            'patientMaritalStatus'     => $this->patientMaritalStatus,
            'patientProfession'        => $this->patientProfession,
            'height'                   => $this->height,
            'heightUnits'              => $this->heightUnits,
            'weight'                   => $this->weight,
            'weightUnits'              => $this->weightUnits,
            'temp'                     => $this->temp,
            'tempUnits'                => $this->tempUnits,
            'bpSystolic'               => $this->bpSystolic,
            'bpDiastolic'              => $this->bpDiastolic,
            'pulse'                    => $this->pulse,
            'glucose'                  => $this->glucose,
            'glucoseUnits'             => $this->glucoseUnits,
            'diagnosis1'               => $this->diagnosis1,
            'condition1'               => $this->condition1,
            'diagnosis2'               => $this->diagnosis2,
            'condition2'               => $this->condition2,
            'diagnosis3'               => $this->diagnosis3,
            'condition3'               => $this->condition3,
            'referredTo'               => $this->referredTo,
            'referredFrom'             => $this->referredFrom,
        ];
    }
}
